// Domande di riserva del form dinamico: scritte a mano, verificate, una
// decina per servizio e per lingua.
//
// Servono alla rete di sicurezza (reteSicurezza.js): se l'AI sbaglia, non
// risponde o propone una domanda che non rispetta i requisiti, il cliente
// riceve una di queste invece di un errore. Dieci bastano a coprire da sole
// un'intera sessione (al massimo 10 domande per servizio).
//
// Regole (le stesse dell'AI, controllate da eval/provaRequisiti.js):
//   - si dà del tu;
//   - quattro opzioni, al massimo una via d'uscita;
//   - niente dati già chiesti dal form (nome, settore, tipo di progetto,
//     budget);
//   - niente logo o font fuori dal branding; per il Logo niente colori e
//     font, che hanno già la loro domanda fissa;
//   - niente punti nel testo della domanda: diventa una chiave nel database.
//
// L'ordine conta: si usa la prima non ancora chiesta, quindi in cima le più
// utili per il preventivo.

const m = (question, options) => ({ question, options });

const RISERVA = {
  Logo: {
    it: [
      m("Che tipo di logo immagini per il tuo brand", ["Solo testo", "Solo simbolo", "Testo e simbolo insieme", "Non saprei, consigliatemi voi"]),
      m("Che sensazione deve trasmettere il logo a chi lo vede", ["Affidabilità e solidità", "Creatività e originalità", "Eleganza e lusso", "Semplicità e immediatezza"]),
      m("Dove verrà usato di più il logo", ["Sito e social", "Insegne e punti vendita", "Packaging e prodotti", "Documenti e biglietti da visita"]),
      m("Preferisci un logo minimale o ricco di dettagli", ["Molto minimale", "Semplice ma con carattere", "Ricco di dettagli", "Non saprei, consigliatemi voi"]),
      m("Quante proposte di logo vorresti vedere all'inizio", ["Una sola, ben ragionata", "Due o tre", "Quattro o più", "Decidete voi"]),
      m("Ti servono anche versioni del logo per usi diversi", ["Sì, orizzontale e verticale", "Sì, anche un'icona per i social", "Basta la versione principale", "Non saprei, consigliatemi voi"]),
      m("Hai già dei loghi di riferimento che ti piacciono", ["Sì, li posso mandare", "Ho qualche idea vaga", "No, parto da zero", "Preferisco evitare riferimenti"]),
      m("Che forma preferisci per il simbolo", ["Geometrica e regolare", "Organica e morbida", "Astratta", "Illustrata o figurativa"]),
      m("Entro quando ti serve il logo definitivo", ["Entro due settimane", "Entro un mese", "Entro tre mesi", "Non ho una scadenza precisa"]),
      m("Ti serve anche un manuale d'uso del logo", ["Sì, completo", "Sì, una guida essenziale", "No, solo i file", "Non saprei, consigliatemi voi"]),
    ],
    en: [
      m("What kind of logo do you have in mind for your brand", ["Text only", "Symbol only", "Text and symbol together", "Not sure, please advise"]),
      m("What feeling should the logo give to people who see it", ["Trust and reliability", "Creativity and originality", "Elegance and luxury", "Simplicity and clarity"]),
      m("Where will the logo be used the most", ["Website and social media", "Signs and stores", "Packaging and products", "Documents and business cards"]),
      m("Do you prefer a minimal logo or a detailed one", ["Very minimal", "Simple but with character", "Rich in detail", "Not sure, please advise"]),
      m("How many logo proposals would you like to see at first", ["Just one, well thought out", "Two or three", "Four or more", "You decide"]),
      m("Do you also need versions of the logo for different uses", ["Yes, horizontal and vertical", "Yes, also an icon for social media", "The main version is enough", "Not sure, please advise"]),
      m("Do you have any reference logos that you like", ["Yes, I can send them", "I have a vague idea", "No, starting from scratch", "I would rather avoid references"]),
      m("What shape do you prefer for the symbol", ["Geometric and regular", "Organic and soft", "Abstract", "Illustrated or figurative"]),
      m("When do you need the final logo", ["Within two weeks", "Within a month", "Within three months", "No fixed deadline"]),
      m("Do you also need a guide on how to use the logo", ["Yes, a complete one", "Yes, a short guide", "No, just the files", "Not sure, please advise"]),
    ],
  },
  "Brand Identity": {
    it: [
      m("Cosa deve comprendere l'identità del tuo brand", ["Logo, colori e caratteri", "Anche il tono di voce", "Anche i materiali stampati", "Non saprei, consigliatemi voi"]),
      m("Che personalità deve avere il tuo brand", ["Professionale e seria", "Giovane e dinamica", "Calda e familiare", "Esclusiva e raffinata"]),
      m("A chi si rivolge soprattutto il tuo brand", ["Privati", "Aziende", "Sia privati sia aziende", "Un pubblico di nicchia"]),
      m("Su quali materiali userai di più l'identità", ["Sito e social", "Stampati e cancelleria", "Punti vendita e allestimenti", "Prodotti e confezioni"]),
      m("Ti serve un manuale con le regole del brand", ["Sì, completo", "Sì, una guida essenziale", "No, bastano i file", "Non saprei, consigliatemi voi"]),
      m("Hai già dei brand che ammiri come riferimento", ["Sì, del mio settore", "Sì, di altri settori", "Qualche idea vaga", "No, preferisco partire da zero"]),
      m("Cosa ti distingue di più dai concorrenti", ["La qualità", "Il prezzo", "Il servizio al cliente", "L'innovazione"]),
      m("Quanto vuoi che il brand cambi rispetto a oggi", ["Poco, solo un aggiornamento", "Abbastanza, restando riconoscibile", "Del tutto, un nuovo inizio", "Non ho ancora un brand"]),
      m("Entro quando ti serve l'identità completa", ["Entro un mese", "Entro tre mesi", "Entro sei mesi", "Non ho una scadenza precisa"]),
      m("Ti servono anche testi come slogan o presentazione", ["Sì, slogan e presentazione", "Solo lo slogan", "No, i testi li ho già", "Non saprei, consigliatemi voi"]),
    ],
    en: [
      m("What should your brand identity include", ["Logo, colors and typefaces", "Also the tone of voice", "Also printed materials", "Not sure, please advise"]),
      m("What personality should your brand have", ["Professional and serious", "Young and dynamic", "Warm and friendly", "Exclusive and refined"]),
      m("Who is your brand mainly for", ["Consumers", "Businesses", "Both consumers and businesses", "A niche audience"]),
      m("Where will you use the identity the most", ["Website and social media", "Print and stationery", "Stores and displays", "Products and packaging"]),
      m("Do you need a manual with the brand rules", ["Yes, a complete one", "Yes, a short guide", "No, the files are enough", "Not sure, please advise"]),
      m("Are there brands you admire as a reference", ["Yes, in my sector", "Yes, in other sectors", "A vague idea", "No, I would rather start from scratch"]),
      m("What sets you apart from your competitors the most", ["Quality", "Price", "Customer service", "Innovation"]),
      m("How much should the brand change compared to today", ["A little, just an update", "Quite a lot, but still recognizable", "Completely, a fresh start", "I do not have a brand yet"]),
      m("When do you need the complete identity", ["Within a month", "Within three months", "Within six months", "No fixed deadline"]),
      m("Do you also need copy such as a slogan or an intro text", ["Yes, slogan and intro text", "Just the slogan", "No, I already have the copy", "Not sure, please advise"]),
    ],
  },
  Packaging: {
    it: [
      m("Che tipo di confezione ti serve", ["Scatola", "Busta o sacchetto", "Etichetta per bottiglia o barattolo", "Non saprei, consigliatemi voi"]),
      m("Quanti prodotti o varianti devono avere la loro confezione", ["Uno solo", "Da due a cinque", "Da sei a dieci", "Più di dieci"]),
      m("Dove verrà venduto soprattutto il prodotto", ["Nei negozi", "Online", "Sia nei negozi sia online", "Alle fiere e agli eventi"]),
      m("Che impressione deve dare la confezione sullo scaffale", ["Premium e raffinata", "Naturale e genuina", "Colorata e allegra", "Tecnica e affidabile"]),
      m("Quanto conta per te la sostenibilità dei materiali", ["È fondamentale", "È importante", "Conta poco", "Non saprei, consigliatemi voi"]),
      m("Ti serve anche il supporto per la stampa", ["Sì, seguite voi la tipografia", "Solo i file pronti per la stampa", "Ho già un fornitore", "Non saprei, consigliatemi voi"]),
      m("Quante confezioni pensi di produrre nel primo lotto", ["Meno di 500", "Da 500 a 5000", "Più di 5000", "Non lo so ancora"]),
      m("Ti servono anche le foto o i rendering della confezione", ["Sì, rendering 3D", "Sì, foto del prodotto finito", "Entrambi", "No, non servono"]),
      m("La confezione deve seguire un'identità già esistente", ["Sì, fedelmente", "Sì, ma con più libertà", "No, è tutto nuovo", "Non saprei, consigliatemi voi"]),
      m("Entro quando ti servono i file definitivi", ["Entro un mese", "Entro tre mesi", "Entro sei mesi", "Non ho una scadenza precisa"]),
    ],
    en: [
      m("What type of packaging do you need", ["Box", "Bag or pouch", "Label for a bottle or jar", "Not sure, please advise"]),
      m("How many products or variants need their own packaging", ["Just one", "Two to five", "Six to ten", "More than ten"]),
      m("Where will the product be sold the most", ["In stores", "Online", "Both in stores and online", "At fairs and events"]),
      m("What impression should the packaging give on the shelf", ["Premium and refined", "Natural and genuine", "Colorful and cheerful", "Technical and reliable"]),
      m("How important is the sustainability of the materials to you", ["Essential", "Important", "Not very important", "Not sure, please advise"]),
      m("Do you also need help with printing", ["Yes, you handle the printer", "Only print-ready files", "I already have a supplier", "Not sure, please advise"]),
      m("How many packages do you plan to produce in the first batch", ["Fewer than 500", "500 to 5000", "More than 5000", "I do not know yet"]),
      m("Do you also need photos or renderings of the packaging", ["Yes, 3D renderings", "Yes, photos of the finished product", "Both", "No, not needed"]),
      m("Should the packaging follow an existing identity", ["Yes, closely", "Yes, but with more freedom", "No, everything is new", "Not sure, please advise"]),
      m("When do you need the final files", ["Within a month", "Within three months", "Within six months", "No fixed deadline"]),
    ],
  },
  "Content Creation": {
    it: [
      m("Che tipo di contenuti ti servono di più", ["Foto", "Video brevi", "Grafiche e caroselli", "Testi e articoli"]),
      m("Per quali canali sono i contenuti", ["Instagram e Facebook", "TikTok", "LinkedIn", "Sito e newsletter"]),
      m("Quanti contenuti ti servono al mese", ["Meno di 5", "Da 5 a 15", "Da 15 a 30", "Più di 30"]),
      m("Qual è l'obiettivo principale dei contenuti", ["Farti conoscere", "Vendere di più", "Fidelizzare i clienti", "Non saprei, consigliatemi voi"]),
      m("Con quale tono vuoi che parlino i tuoi contenuti", ["Professionale", "Ironico e leggero", "Ispirazionale", "Informativo"]),
      m("Chi si occupa oggi dei tuoi contenuti", ["Nessuno, partiamo da zero", "Io, nel tempo libero", "Un collaboratore interno", "Un'altra agenzia"]),
      m("Ti serve anche il piano editoriale", ["Sì, lo preparate voi", "Lo prepariamo insieme", "No, ce l'ho già", "Non saprei, consigliatemi voi"]),
      m("Servono riprese o scatti sul posto", ["Sì, da noi", "Sì, in esterna", "No, bastano materiali che ho", "Non saprei, consigliatemi voi"]),
      m("Chi deve comparire nei contenuti", ["Io o il mio team", "I prodotti", "I clienti", "Nessuno, solo grafiche"]),
      m("Per quanto tempo pensi di aver bisogno dei contenuti", ["Un solo mese di prova", "Tre mesi", "Sei mesi", "Un anno o più"]),
    ],
    en: [
      m("What kind of content do you need the most", ["Photos", "Short videos", "Graphics and carousels", "Copy and articles"]),
      m("Which channels is the content for", ["Instagram and Facebook", "TikTok", "LinkedIn", "Website and newsletter"]),
      m("How many pieces of content do you need per month", ["Fewer than 5", "5 to 15", "15 to 30", "More than 30"]),
      m("What is the main goal of the content", ["Getting known", "Selling more", "Keeping customers loyal", "Not sure, please advise"]),
      m("What tone should the content have", ["Professional", "Playful and light", "Inspirational", "Informative"]),
      m("Who takes care of your content today", ["Nobody, we start from scratch", "Me, in my spare time", "Someone on my team", "Another agency"]),
      m("Do you also need an editorial plan", ["Yes, you prepare it", "We prepare it together", "No, I already have one", "Not sure, please advise"]),
      m("Do you need photo or video shoots on location", ["Yes, at our place", "Yes, outdoors", "No, the material I have is enough", "Not sure, please advise"]),
      m("Who should appear in the content", ["Me or my team", "The products", "The customers", "Nobody, only graphics"]),
      m("For how long do you think you will need the content", ["Just one trial month", "Three months", "Six months", "A year or more"]),
    ],
  },
  "Social Media Management": {
    it: [
      m("Quali profili social vuoi farci gestire", ["Instagram", "Facebook", "LinkedIn", "TikTok"]),
      m("Quante pubblicazioni a settimana ti aspetti", ["Una o due", "Da tre a cinque", "Tutti i giorni", "Non saprei, consigliatemi voi"]),
      m("Qual è l'obiettivo principale sui social", ["Più follower", "Più contatti e richieste", "Più vendite", "Più riconoscibilità"]),
      m("Vuoi che siamo noi a rispondere a commenti e messaggi", ["Sì, a tutto", "Solo ai commenti", "No, rispondo io", "Non saprei, consigliatemi voi"]),
      m("Com'è oggi la situazione dei tuoi profili", ["Non esistono ancora", "Esistono ma sono fermi", "Li aggiorno ogni tanto", "Sono attivi e seguiti"]),
      m("Ti serve un report periodico dei risultati", ["Sì, ogni mese", "Sì, ogni tre mesi", "No, non serve", "Non saprei, consigliatemi voi"]),
      m("Vuoi abbinare anche delle sponsorizzate", ["Sì, fin da subito", "Più avanti", "No", "Non saprei, consigliatemi voi"]),
      m("Chi fornisce foto e video per i post", ["Li fornisco io", "Li create voi", "Un po' e un po'", "Non saprei, consigliatemi voi"]),
      m("Con quale tono devi parlare al tuo pubblico", ["Formale", "Amichevole", "Divertente", "Tecnico"]),
      m("Per quanto tempo vorresti la gestione", ["Tre mesi di prova", "Sei mesi", "Un anno", "Senza scadenza"]),
    ],
    en: [
      m("Which social profiles would you like us to manage", ["Instagram", "Facebook", "LinkedIn", "TikTok"]),
      m("How many posts per week do you expect", ["One or two", "Three to five", "Every day", "Not sure, please advise"]),
      m("What is your main goal on social media", ["More followers", "More leads and inquiries", "More sales", "More brand awareness"]),
      m("Should we reply to comments and messages", ["Yes, to everything", "Only to comments", "No, I will reply", "Not sure, please advise"]),
      m("What is the current state of your profiles", ["They do not exist yet", "They exist but are inactive", "I update them now and then", "They are active and followed"]),
      m("Do you need a regular report on the results", ["Yes, every month", "Yes, every three months", "No, not needed", "Not sure, please advise"]),
      m("Would you like to add paid ads as well", ["Yes, right away", "Later on", "No", "Not sure, please advise"]),
      m("Who provides the photos and videos for the posts", ["I will provide them", "You create them", "A bit of both", "Not sure, please advise"]),
      m("What tone should you use with your audience", ["Formal", "Friendly", "Funny", "Technical"]),
      m("For how long would you like the management", ["A three-month trial", "Six months", "One year", "No end date"]),
    ],
  },
  Advertising: {
    it: [
      m("Dove vuoi fare pubblicità", ["Instagram e Facebook", "Google", "LinkedIn", "Non saprei, consigliatemi voi"]),
      m("Qual è l'obiettivo principale delle campagne", ["Vendite online", "Contatti e richieste", "Visite al negozio", "Farti conoscere"]),
      m("Hai già fatto campagne a pagamento", ["No, mai", "Sì, da solo", "Sì, con un'agenzia", "Sì, ma senza risultati"]),
      m("A chi vuoi mostrare gli annunci", ["Persone della mia zona", "Tutta Italia", "Anche all'estero", "Non saprei, consigliatemi voi"]),
      m("Ti servono anche le grafiche e i video degli annunci", ["Sì, tutto", "Solo le grafiche", "No, li ho già", "Non saprei, consigliatemi voi"]),
      m("Per quanto tempo vuoi far girare le campagne", ["Un mese di prova", "Tre mesi", "Sei mesi o più", "Solo per un evento o una promozione"]),
      m("Dove deve arrivare chi clicca sull'annuncio", ["Al sito", "A un negozio online", "A una pagina dedicata", "A un contatto diretto"]),
      m("Hai un sito pronto a ricevere le visite delle campagne", ["Sì, funziona bene", "Sì, ma va migliorato", "No, non ce l'ho", "Non saprei"]),
      m("Ogni quanto vuoi vedere i risultati", ["Ogni settimana", "Ogni mese", "Alla fine della campagna", "Non saprei, consigliatemi voi"]),
      m("C'è un periodo dell'anno in cui vendi di più", ["Sì, d'estate", "Sì, sotto le feste", "No, vendo tutto l'anno", "Non lo so"]),
    ],
    en: [
      m("Where would you like to advertise", ["Instagram and Facebook", "Google", "LinkedIn", "Not sure, please advise"]),
      m("What is the main goal of the campaigns", ["Online sales", "Leads and inquiries", "Store visits", "Getting known"]),
      m("Have you run paid campaigns before", ["No, never", "Yes, on my own", "Yes, with an agency", "Yes, but with no results"]),
      m("Who should see the ads", ["People in my area", "The whole country", "Also abroad", "Not sure, please advise"]),
      m("Do you also need the graphics and videos for the ads", ["Yes, all of it", "Just the graphics", "No, I already have them", "Not sure, please advise"]),
      m("For how long would you like to run the campaigns", ["A one-month trial", "Three months", "Six months or more", "Only for an event or a promotion"]),
      m("Where should people land when they click the ad", ["On the website", "On an online store", "On a dedicated page", "On a direct contact"]),
      m("Is your website ready to receive the traffic from the campaigns", ["Yes, it works well", "Yes, but it needs work", "No, I do not have one", "I do not know"]),
      m("How often would you like to see the results", ["Every week", "Every month", "At the end of the campaign", "Not sure, please advise"]),
      m("Is there a time of year when you sell the most", ["Yes, in summer", "Yes, during the holidays", "No, all year round", "I do not know"]),
    ],
  },
  "Product Photography": {
    it: [
      m("Quanti sono i prodotti da fotografare", ["Meno di 10", "Da 10 a 50", "Da 50 a 200", "Più di 200"]),
      m("Che tipo di foto ti servono", ["Su sfondo bianco", "Ambientate", "Dettagli e particolari", "Non saprei, consigliatemi voi"]),
      m("Dove userai soprattutto le foto", ["Negozio online", "Social", "Catalogo stampato", "Marketplace come Amazon"]),
      m("Quante foto ti servono per ciascun prodotto", ["Una", "Da due a quattro", "Più di quattro", "Non saprei, consigliatemi voi"]),
      m("Dove preferisci che si faccia lo shooting", ["Nel vostro studio", "Da me", "In una location scelta insieme", "Non saprei, consigliatemi voi"]),
      m("Servono anche foto con persone che usano il prodotto", ["Sì, con modelli", "Sì, con mani in primo piano", "No, solo il prodotto", "Non saprei, consigliatemi voi"]),
      m("Ti servono anche brevi video dei prodotti", ["Sì, per tutti", "Sì, per alcuni", "No", "Non saprei, consigliatemi voi"]),
      m("Quanto ritocco ti serve sulle foto", ["Leggero e naturale", "Accurato", "Molto accurato, da catalogo", "Non saprei, consigliatemi voi"]),
      m("Com'è fatto soprattutto il prodotto", ["Piccolo e maneggevole", "Grande o ingombrante", "Riflettente come vetro o metallo", "Alimentare"]),
      m("Entro quando ti servono le foto", ["Entro due settimane", "Entro un mese", "Entro tre mesi", "Non ho una scadenza precisa"]),
    ],
    en: [
      m("How many products need to be photographed", ["Fewer than 10", "10 to 50", "50 to 200", "More than 200"]),
      m("What kind of photos do you need", ["On a white background", "In a setting", "Close-ups and details", "Not sure, please advise"]),
      m("Where will you use the photos the most", ["Online store", "Social media", "Printed catalog", "Marketplaces like Amazon"]),
      m("How many photos do you need for each product", ["One", "Two to four", "More than four", "Not sure, please advise"]),
      m("Where would you like the shoot to take place", ["In your studio", "At my place", "At a location we choose together", "Not sure, please advise"]),
      m("Do you also need photos of people using the product", ["Yes, with models", "Yes, with close-ups of hands", "No, just the product", "Not sure, please advise"]),
      m("Do you also need short videos of the products", ["Yes, for all of them", "Yes, for some", "No", "Not sure, please advise"]),
      m("How much retouching do the photos need", ["Light and natural", "Careful", "Very careful, catalog quality", "Not sure, please advise"]),
      m("What is the product mostly like", ["Small and easy to handle", "Large or bulky", "Reflective like glass or metal", "Food"]),
      m("What is your deadline for the final images", ["Within two weeks", "Within a month", "Within three months", "No fixed deadline"]),
    ],
  },
  "Fashion Photography": {
    it: [
      m("Che tipo di servizio fotografico ti serve", ["Catalogo o lookbook", "Campagna pubblicitaria", "Foto per il negozio online", "Non saprei, consigliatemi voi"]),
      m("Quanti capi o outfit vanno fotografati", ["Meno di 10", "Da 10 a 30", "Da 30 a 100", "Più di 100"]),
      m("Dove preferisci scattare", ["In studio", "In esterna, in città", "In una location particolare", "Non saprei, consigliatemi voi"]),
      m("Ti servono anche i modelli o le modelle", ["Sì, li cercate voi", "No, li ho già", "Solo foto dei capi senza modelli", "Non saprei, consigliatemi voi"]),
      m("Ti servono anche trucco, capelli e styling", ["Sì, tutto", "Solo trucco e capelli", "No", "Non saprei, consigliatemi voi"]),
      m("Dove userai soprattutto le foto", ["Negozio online", "Social", "Stampa e riviste", "Stampati per il punto vendita"]),
      m("Che atmosfera devono avere le foto", ["Pulita e minimale", "Elegante e sofisticata", "Urbana e spontanea", "Artistica e d'impatto"]),
      m("Servono anche video del servizio", ["Sì, video promozionali", "Sì, brevi clip per i social", "No", "Non saprei, consigliatemi voi"]),
      m("Per quale stagione o collezione sono le foto", ["Primavera e estate", "Autunno e inverno", "Senza stagione", "Una capsule o un'edizione speciale"]),
      m("Entro quando ti servono le foto", ["Entro due settimane", "Entro un mese", "Entro tre mesi", "Non ho una scadenza precisa"]),
    ],
    en: [
      m("What kind of photo shoot do you need", ["Catalog or lookbook", "Advertising campaign", "Photos for the online store", "Not sure, please advise"]),
      m("How many garments or outfits need to be photographed", ["Fewer than 10", "10 to 30", "30 to 100", "More than 100"]),
      m("Where would you like to shoot", ["In a studio", "Outdoors, in the city", "At a special location", "Not sure, please advise"]),
      m("Do you also need models", ["Yes, you find them", "No, I already have them", "Only product shots without models", "Not sure, please advise"]),
      m("Do you also need makeup, hair and styling", ["Yes, all of it", "Just makeup and hair", "No", "Not sure, please advise"]),
      m("Where will you use the photos the most", ["Online store", "Social media", "Press and magazines", "In-store print materials"]),
      m("What mood should the photos have", ["Clean and minimal", "Elegant and sophisticated", "Urban and spontaneous", "Artistic and striking"]),
      m("Do you also need videos from the shoot", ["Yes, promotional videos", "Yes, short clips for social media", "No", "Not sure, please advise"]),
      m("Which season or collection are the photos for", ["Spring and summer", "Fall and winter", "Seasonless", "A capsule or special edition"]),
      m("What is your deadline for the final images", ["Within two weeks", "Within a month", "Within three months", "No fixed deadline"]),
    ],
  },
  "Event Photography": {
    it: [
      m("Che tipo di evento devi far fotografare", ["Aziendale o convegno", "Festa o inaugurazione", "Fiera", "Spettacolo o concerto"]),
      m("Quanto dura l'evento", ["Meno di due ore", "Mezza giornata", "Una giornata intera", "Più giorni"]),
      m("Quante persone parteciperanno all'evento", ["Meno di 50", "Da 50 a 200", "Da 200 a 1000", "Più di 1000"]),
      m("Dove si svolge l'evento", ["Nella mia città", "In un'altra città italiana", "All'estero", "Non è ancora deciso"]),
      m("Ti serve anche un video dell'evento", ["Sì, un video completo", "Sì, un breve riassunto", "No", "Non saprei, consigliatemi voi"]),
      m("Entro quando ti servono le foto dopo l'evento", ["Il giorno stesso", "Entro una settimana", "Entro due settimane", "Non ho fretta"]),
      m("Cosa è più importante fotografare", ["Gli interventi sul palco", "Le persone e l'atmosfera", "Gli allestimenti e i prodotti", "Un po' di tutto"]),
      m("Dove userai soprattutto le foto", ["Social", "Sito", "Comunicati e stampa", "Archivio interno"]),
      m("Servono ritratti degli ospiti o dei relatori", ["Sì, posati", "Sì, spontanei", "No", "Non saprei, consigliatemi voi"]),
      m("Tra quanto tempo è in programma", ["Entro un mese", "Tra uno e tre mesi", "Tra più di tre mesi", "La data non è ancora decisa"]),
    ],
    en: [
      m("What type of event needs to be photographed", ["Corporate event or conference", "Party or opening", "Trade fair", "Show or concert"]),
      m("How long does the event last", ["Less than two hours", "Half a day", "A full day", "Several days"]),
      m("How many people will attend the event", ["Fewer than 50", "50 to 200", "200 to 1000", "More than 1000"]),
      m("Where does the event take place", ["In my city", "In another city", "Abroad", "Not decided yet"]),
      m("Do you also need a video of the event", ["Yes, a full video", "Yes, a short recap", "No", "Not sure, please advise"]),
      m("How soon do you need the photos after the event", ["The same day", "Within a week", "Within two weeks", "I am in no hurry"]),
      m("What matters most to photograph", ["The talks on stage", "The people and the atmosphere", "The setup and the products", "A bit of everything"]),
      m("Where will you use the photos the most", ["Social media", "Website", "Press releases", "Internal archive"]),
      m("Do you need portraits of the guests or speakers", ["Yes, posed", "Yes, candid", "No", "Not sure, please advise"]),
      m("How soon is it scheduled", ["Within a month", "In one to three months", "In more than three months", "The date is not set yet"]),
    ],
  },
  "Promo Video": {
    it: [
      m("Quanto deve durare il video", ["Meno di 30 secondi", "Da 30 secondi a un minuto", "Da uno a tre minuti", "Non saprei, consigliatemi voi"]),
      m("Dove verrà pubblicato soprattutto il video", ["Instagram e TikTok", "YouTube", "Sito", "Pubblicità a pagamento"]),
      m("Cosa deve promuovere il video", ["Un prodotto", "Un servizio", "Un evento", "L'azienda in generale"]),
      m("Che stile deve avere il video", ["Emozionale", "Dinamico e veloce", "Divertente", "Elegante"]),
      m("Ti serve anche la sceneggiatura", ["Sì, la scrivete voi", "La scriviamo insieme", "No, ce l'ho già", "Non saprei, consigliatemi voi"]),
      m("Chi deve comparire nel video", ["Attori o modelli", "Io o il mio team", "Solo i prodotti", "Nessuno, solo grafica"]),
      m("Dove si devono fare le riprese", ["Da me", "In studio", "In esterna", "Non saprei, consigliatemi voi"]),
      m("Ti servono più versioni del video", ["Sì, orizzontale e verticale", "Sì, anche versioni brevi", "No, una sola", "Non saprei, consigliatemi voi"]),
      m("Ti servono una voce fuori campo o i sottotitoli", ["Voce fuori campo", "Sottotitoli", "Entrambi", "Nessuno dei due"]),
      m("Entro quando ti serve il video", ["Entro due settimane", "Entro un mese", "Entro tre mesi", "Non ho una scadenza precisa"]),
    ],
    en: [
      m("How long should the video be", ["Less than 30 seconds", "30 seconds to one minute", "One to three minutes", "Not sure, please advise"]),
      m("Where will the video be published the most", ["Instagram and TikTok", "YouTube", "Website", "Paid ads"]),
      m("What should the video promote", ["A product", "A service", "An event", "The company in general"]),
      m("What style should the video have", ["Emotional", "Dynamic and fast", "Funny", "Elegant"]),
      m("Do you also need the script", ["Yes, you write it", "We write it together", "No, I already have one", "Not sure, please advise"]),
      m("Who should appear in the video", ["Actors or models", "Me or my team", "Only the products", "Nobody, just graphics"]),
      m("Where should the video be shot", ["At my place", "In a studio", "Outdoors", "Not sure, please advise"]),
      m("Do you need several versions of the video", ["Yes, horizontal and vertical", "Yes, also short cuts", "No, just one", "Not sure, please advise"]),
      m("Do you need a voice-over or subtitles", ["Voice-over", "Subtitles", "Both", "Neither"]),
      m("What is your deadline for the final cut", ["Within two weeks", "Within a month", "Within three months", "No fixed deadline"]),
    ],
  },
  "Corporate Video": {
    it: [
      m("A cosa serve il video aziendale", ["Presentare l'azienda", "Cercare personale", "Formazione interna", "Presentarsi agli investitori"]),
      m("Quanto deve durare il video", ["Meno di un minuto", "Da uno a tre minuti", "Da tre a cinque minuti", "Non saprei, consigliatemi voi"]),
      m("Chi deve comparire nel video", ["I titolari", "I dipendenti", "I clienti", "Nessuno, solo luoghi e prodotti"]),
      m("Dove si devono fare le riprese", ["In sede", "In più sedi", "Anche all'estero", "Non saprei, consigliatemi voi"]),
      m("Vuoi che ci siano delle interviste", ["Sì, più di una", "Sì, una sola", "No", "Non saprei, consigliatemi voi"]),
      m("Dove verrà mostrato soprattutto il video", ["Sito", "LinkedIn", "Fiere ed eventi", "Riunioni e presentazioni"]),
      m("Che tono deve avere il video", ["Istituzionale", "Umano e vicino", "Moderno e dinamico", "Tecnico"]),
      m("Ti serve il video anche in altre lingue", ["Sì, con sottotitoli", "Sì, con voce doppiata", "No", "Non saprei, consigliatemi voi"]),
      m("Servono riprese aeree con il drone", ["Sì", "Solo se la sede lo merita", "No", "Non saprei, consigliatemi voi"]),
      m("Entro quando ti serve il video", ["Entro un mese", "Entro tre mesi", "Entro sei mesi", "Non ho una scadenza precisa"]),
    ],
    en: [
      m("What is the corporate video for", ["Presenting the company", "Hiring", "Internal training", "Pitching to investors"]),
      m("How long should the video be", ["Less than one minute", "One to three minutes", "Three to five minutes", "Not sure, please advise"]),
      m("Who should appear in the video", ["The owners", "The employees", "The customers", "Nobody, just places and products"]),
      m("Where should the video be shot", ["At our offices", "At several locations", "Also abroad", "Not sure, please advise"]),
      m("Do you need interviews in the video", ["Yes, more than one", "Yes, just one", "No", "Not sure, please advise"]),
      m("Where will the video be shown the most", ["Website", "LinkedIn", "Trade fairs and events", "Meetings and presentations"]),
      m("What tone should the video have", ["Institutional", "Human and close", "Modern and dynamic", "Technical"]),
      m("Do you need the video in other languages too", ["Yes, with subtitles", "Yes, with dubbing", "No", "Not sure, please advise"]),
      m("Do you need aerial drone footage", ["Yes", "Only if the location deserves it", "No", "Not sure, please advise"]),
      m("What is your deadline for the final cut", ["Within a month", "Within three months", "Within six months", "No fixed deadline"]),
    ],
  },
  "Motion Graphics": {
    it: [
      m("Che tipo di animazione ti serve", ["Video esplicativo", "Animazioni per i social", "Intro o sigla", "Infografica animata"]),
      m("Quanto deve durare l'animazione", ["Meno di 15 secondi", "Da 15 secondi a un minuto", "Da uno a tre minuti", "Non saprei, consigliatemi voi"]),
      m("Che stile grafico preferisci", ["Piatto e minimale", "Illustrato", "In 3D", "Non saprei, consigliatemi voi"]),
      m("Ti servono anche i testi e la sceneggiatura", ["Sì, li scrivete voi", "Li scriviamo insieme", "No, li ho già", "Non saprei, consigliatemi voi"]),
      m("Ti servono una voce fuori campo e la musica", ["Voce e musica", "Solo musica", "Solo voce", "Nessuna delle due"]),
      m("Dove verrà usata soprattutto l'animazione", ["Social", "Sito", "Presentazioni", "Pubblicità"]),
      m("Quante animazioni ti servono", ["Una", "Da due a cinque", "Più di cinque", "Un servizio continuativo"]),
      m("Hai già grafiche o illustrazioni da animare", ["Sì, tutte", "Sì, in parte", "No, vanno create", "Non saprei"]),
      m("Ti servono più formati dell'animazione", ["Sì, orizzontale e verticale", "Sì, anche quadrato", "No, uno solo", "Non saprei, consigliatemi voi"]),
      m("Entro quando ti serve l'animazione", ["Entro due settimane", "Entro un mese", "Entro tre mesi", "Non ho una scadenza precisa"]),
    ],
    en: [
      m("What kind of animation do you need", ["Explainer video", "Animations for social media", "Intro or opener", "Animated infographic"]),
      m("How long should the animation be", ["Less than 15 seconds", "15 seconds to one minute", "One to three minutes", "Not sure, please advise"]),
      m("Which graphic style do you prefer", ["Flat and minimal", "Illustrated", "3D", "Not sure, please advise"]),
      m("Do you also need the copy and the script", ["Yes, you write them", "We write them together", "No, I already have them", "Not sure, please advise"]),
      m("Do you need a voice-over and music", ["Voice-over and music", "Music only", "Voice-over only", "Neither"]),
      m("Where will the animation be used the most", ["Social media", "Website", "Presentations", "Advertising"]),
      m("How many animations do you need", ["One", "Two to five", "More than five", "An ongoing service"]),
      m("Do you already have graphics or illustrations to animate", ["Yes, all of them", "Yes, some", "No, they need to be created", "I do not know"]),
      m("Do you need the animation in several formats", ["Yes, horizontal and vertical", "Yes, also square", "No, just one", "Not sure, please advise"]),
      m("What is your deadline for delivery", ["Within two weeks", "Within a month", "Within three months", "No fixed deadline"]),
    ],
  },
  "Website Design": {
    it: [
      m("Che tipo di sito ti serve", ["Sito vetrina", "Sito con blog", "Sito con prenotazioni", "Non saprei, consigliatemi voi"]),
      m("Quante pagine pensi che debba avere il sito", ["Una sola pagina", "Da 2 a 5", "Da 6 a 15", "Più di 15"]),
      m("Qual è l'obiettivo principale del sito", ["Farti conoscere", "Ricevere contatti", "Vendere", "Dare informazioni ai clienti"]),
      m("Hai già i testi e le immagini del sito", ["Sì, tutto", "Solo in parte", "No, servono anche quelli", "Non saprei"]),
      m("Vuoi poter modificare il sito da solo", ["Sì, spesso", "Ogni tanto", "No, preferisco che lo facciate voi", "Non saprei, consigliatemi voi"]),
      m("In quante lingue deve essere il sito", ["Solo italiano", "Italiano e inglese", "Tre o più lingue", "Non saprei, consigliatemi voi"]),
      m("Hai già un dominio e un hosting", ["Sì, entrambi", "Solo il dominio", "No, nessuno dei due", "Non lo so"]),
      m("Ti serve anche il posizionamento sui motori di ricerca", ["Sì, fin da subito", "Più avanti", "No", "Non saprei, consigliatemi voi"]),
      m("Ti serve assistenza dopo la pubblicazione", ["Sì, continuativa", "Solo per i primi mesi", "No", "Non saprei, consigliatemi voi"]),
      m("Entro quando vorresti il sito online", ["Entro un mese", "Entro tre mesi", "Entro sei mesi", "Non ho una scadenza precisa"]),
    ],
    en: [
      m("What type of website do you need", ["Showcase website", "Website with a blog", "Website with bookings", "Not sure, please advise"]),
      m("How many pages do you think the website should have", ["A single page", "2 to 5", "6 to 15", "More than 15"]),
      m("What is the main goal of the website", ["Getting known", "Getting inquiries", "Selling", "Informing customers"]),
      m("Do you already have the copy and images for the website", ["Yes, all of it", "Only some of it", "No, I need those too", "I do not know"]),
      m("Would you like to be able to edit the website yourself", ["Yes, often", "Now and then", "No, I would rather you do it", "Not sure, please advise"]),
      m("How many languages should the website be in", ["Just one", "Two", "Three or more", "Not sure, please advise"]),
      m("Do you already have a domain and hosting", ["Yes, both", "Just the domain", "No, neither", "I do not know"]),
      m("Do you also need search engine optimization", ["Yes, right away", "Later on", "No", "Not sure, please advise"]),
      m("Do you need support after the launch", ["Yes, ongoing", "Only for the first months", "No", "Not sure, please advise"]),
      m("When would you like the website to go live", ["Within a month", "Within three months", "Within six months", "No fixed deadline"]),
    ],
  },
  "E-commerce": {
    it: [
      m("Quanti sono i prodotti che vuoi vendere online", ["Meno di 20", "Da 20 a 100", "Da 100 a 1000", "Più di 1000"]),
      m("Su quale piattaforma vorresti il negozio", ["Shopify", "WooCommerce", "Una soluzione su misura", "Non saprei, consigliatemi voi"]),
      m("Hai già un negozio online da rifare", ["Sì, da migliorare", "Sì, da rifare da capo", "No, parto da zero", "Vendo solo sui marketplace"]),
      m("Dove vuoi spedire i prodotti", ["Solo in Italia", "In Europa", "In tutto il mondo", "Non spedisco, solo ritiro"]),
      m("Quali pagamenti vuoi accettare", ["Carte e PayPal", "Anche bonifico", "Anche pagamento alla consegna", "Non saprei, consigliatemi voi"]),
      m("Chi si occuperà di caricare i prodotti", ["Io", "Voi", "Un po' e un po'", "Non saprei, consigliatemi voi"]),
      m("Il negozio deve collegarsi a un gestionale o al magazzino", ["Sì, a un gestionale", "Sì, a un magazzino esterno", "No", "Non lo so"]),
      m("Ti servono anche le foto dei prodotti", ["Sì, tutte", "Solo per alcuni prodotti", "No, le ho già", "Non saprei, consigliatemi voi"]),
      m("In quante lingue deve essere il negozio", ["Solo italiano", "Italiano e inglese", "Tre o più lingue", "Non saprei, consigliatemi voi"]),
      m("Entro quando vorresti iniziare a vendere online", ["Entro un mese", "Entro tre mesi", "Entro sei mesi", "Non ho una scadenza precisa"]),
    ],
    en: [
      m("How many products will you sell online", ["Fewer than 20", "20 to 100", "100 to 1000", "More than 1000"]),
      m("Which platform would you like for the store", ["Shopify", "WooCommerce", "A custom solution", "Not sure, please advise"]),
      m("Do you already have an online store to redo", ["Yes, to improve", "Yes, to rebuild from scratch", "No, starting from scratch", "I only sell on marketplaces"]),
      m("Where do you want to ship the products", ["Only in my country", "Across Europe", "Worldwide", "No shipping, pickup only"]),
      m("Which payments do you want to accept", ["Cards and PayPal", "Also bank transfer", "Also cash on delivery", "Not sure, please advise"]),
      m("Who will take care of uploading the products", ["Me", "You", "A bit of both", "Not sure, please advise"]),
      m("Should the store connect to a management system or warehouse", ["Yes, to a management system", "Yes, to an external warehouse", "No", "I do not know"]),
      m("Do you also need photos of the products", ["Yes, all of them", "Only for some products", "No, I already have them", "Not sure, please advise"]),
      m("How many languages should the store be in", ["Just one", "Two", "Three or more", "Not sure, please advise"]),
      m("When would you like to start selling online", ["Within a month", "Within three months", "Within six months", "No fixed deadline"]),
    ],
  },
  "Landing Page": {
    it: [
      m("A cosa serve la landing page", ["Raccogliere contatti", "Vendere un prodotto", "Promuovere un evento", "Lanciare una campagna"]),
      m("Da dove arriveranno le visite alla pagina", ["Pubblicità sui social", "Pubblicità su Google", "Newsletter", "Non saprei, consigliatemi voi"]),
      m("Cosa deve fare chi arriva sulla pagina", ["Compilare un modulo", "Acquistare", "Prenotare", "Scaricare un contenuto"]),
      m("Hai già i testi della pagina", ["Sì", "In parte", "No, servono anche quelli", "Non saprei"]),
      m("Ti servono più versioni della pagina da confrontare", ["Sì, due versioni", "Sì, più di due", "No, una sola", "Non saprei, consigliatemi voi"]),
      m("Dove vuoi ricevere i contatti raccolti dalla pagina", ["Per email", "In un CRM", "In un foglio di calcolo", "Non saprei, consigliatemi voi"]),
      m("Per quanto tempo resterà online la pagina", ["Poche settimane", "Qualche mese", "Senza scadenza", "Non lo so ancora"]),
      m("Ti servono immagini o video per la pagina", ["Sì, foto", "Sì, un video", "No, li ho già", "Non saprei, consigliatemi voi"]),
      m("Vuoi misurare i risultati della pagina", ["Sì, in dettaglio", "Sì, i numeri principali", "No", "Non saprei, consigliatemi voi"]),
      m("Entro quando ti serve la pagina online", ["Entro una settimana", "Entro due settimane", "Entro un mese", "Non ho una scadenza precisa"]),
    ],
    en: [
      m("What is the landing page for", ["Collecting leads", "Selling a product", "Promoting an event", "Launching a campaign"]),
      m("Where will the visits to the page come from", ["Social media ads", "Google ads", "Newsletter", "Not sure, please advise"]),
      m("What should visitors do on the page", ["Fill in a form", "Buy", "Book", "Download something"]),
      m("Do you already have the copy for the page", ["Yes", "Partly", "No, I need that too", "I do not know"]),
      m("Do you need several versions of the page to compare", ["Yes, two versions", "Yes, more than two", "No, just one", "Not sure, please advise"]),
      m("Where should the collected leads go", ["By email", "Into a CRM", "Into a spreadsheet", "Not sure, please advise"]),
      m("For how long will the page stay online", ["A few weeks", "A few months", "With no end date", "I do not know yet"]),
      m("Do you need images or video for the page", ["Yes, photos", "Yes, a video", "No, I already have them", "Not sure, please advise"]),
      m("Would you like to measure how the page performs", ["Yes, in detail", "Yes, the main numbers", "No", "Not sure, please advise"]),
      m("When do you need the page to go live", ["Within a week", "Within two weeks", "Within a month", "No fixed deadline"]),
    ],
  },
  "Mobile App": {
    it: [
      m("Su quali telefoni deve funzionare l'app", ["iPhone", "Android", "Entrambi", "Non saprei, consigliatemi voi"]),
      m("A cosa serve soprattutto l'app", ["Vendere", "Prenotare", "Offrire un servizio ai clienti", "Uso interno all'azienda"]),
      m("Gli utenti devono registrarsi per usare l'app", ["Sì, sempre", "Solo per alcune funzioni", "No", "Non saprei, consigliatemi voi"]),
      m("Vuoi che nell'app si possa pagare", ["Sì, acquisti", "Sì, abbonamenti", "No", "Non saprei, consigliatemi voi"]),
      m("Ti servono le notifiche sul telefono", ["Sì", "No", "Più avanti", "Non saprei, consigliatemi voi"]),
      m("A che punto è l'idea dell'app", ["Solo un'idea", "Ho già delle bozze", "Ho già un progetto dettagliato", "Esiste già e va rifatta"]),
      m("L'app deve collegarsi a sistemi che usi già", ["Sì, al gestionale", "Sì, al sito", "No", "Non lo so"]),
      m("Quante persone pensi che la useranno nel primo anno", ["Meno di 100", "Da 100 a 1000", "Da 1000 a 10000", "Più di 10000"]),
      m("Ti serve anche la pubblicazione sugli store", ["Sì, la seguite voi", "No, la faccio io", "Non saprei, consigliatemi voi", "Non la voglio pubblicare"]),
      m("Entro quando vorresti la prima versione dell'app", ["Entro tre mesi", "Entro sei mesi", "Entro un anno", "Non ho una scadenza precisa"]),
    ],
    en: [
      m("Which phones should the app work on", ["iPhone", "Android", "Both", "Not sure, please advise"]),
      m("What is the app mainly for", ["Selling", "Booking", "Offering a service to customers", "Internal company use"]),
      m("Do users need to sign up to use the app", ["Yes, always", "Only for some features", "No", "Not sure, please advise"]),
      m("Should the app accept payments", ["Yes, purchases", "Yes, subscriptions", "No", "Not sure, please advise"]),
      m("Do you need push notifications", ["Yes", "No", "Later on", "Not sure, please advise"]),
      m("How far along is the app idea", ["Just an idea", "I have some sketches", "I have a detailed plan", "It exists and needs a rebuild"]),
      m("Should the app connect to systems you already use", ["Yes, to the management system", "Yes, to the website", "No", "I do not know"]),
      m("How many people do you think will use it in the first year", ["Fewer than 100", "100 to 1000", "1000 to 10000", "More than 10000"]),
      m("Do you also need help publishing it on the app stores", ["Yes, you handle it", "No, I will do it", "Not sure, please advise", "I do not want to publish it"]),
      m("When would you like the first version of the app", ["Within three months", "Within six months", "Within a year", "No fixed deadline"]),
    ],
  },
  "Web App": {
    it: [
      m("A cosa serve soprattutto la web app", ["Gestire il lavoro interno", "Offrire un servizio ai clienti", "Vendere abbonamenti", "Non saprei, consigliatemi voi"]),
      m("Chi userà la web app", ["Solo il mio team", "I miei clienti", "Entrambi", "Chiunque, aperta al pubblico"]),
      m("Quante persone la useranno all'inizio", ["Meno di 10", "Da 10 a 100", "Da 100 a 1000", "Più di 1000"]),
      m("Servono ruoli e permessi diversi tra gli utenti", ["Sì, molti ruoli", "Sì, due o tre", "No, tutti uguali", "Non saprei, consigliatemi voi"]),
      m("Vuoi che la web app si colleghi ad altri programmi", ["Sì, al gestionale", "Sì, a strumenti di pagamento", "No", "Non lo so"]),
      m("A che punto è il progetto", ["Solo un'idea", "Ho già delle bozze", "Ho un documento con i requisiti", "Esiste già e va rifatta"]),
      m("Deve funzionare bene anche da telefono", ["Sì, soprattutto da telefono", "Sì, ma si usa più da computer", "No, solo da computer", "Non saprei, consigliatemi voi"]),
      m("Ti servono report o statistiche dentro la web app", ["Sì, dettagliati", "Sì, essenziali", "No", "Non saprei, consigliatemi voi"]),
      m("Ti serve assistenza dopo il lancio", ["Sì, continuativa", "Solo per i primi mesi", "No", "Non saprei, consigliatemi voi"]),
      m("Entro quando vorresti la prima versione", ["Entro tre mesi", "Entro sei mesi", "Entro un anno", "Non ho una scadenza precisa"]),
    ],
    en: [
      m("What is the web app mainly for", ["Managing internal work", "Offering a service to customers", "Selling subscriptions", "Not sure, please advise"]),
      m("Who will use the web app", ["Only my team", "My customers", "Both", "Anyone, open to the public"]),
      m("How many people will use it at first", ["Fewer than 10", "10 to 100", "100 to 1000", "More than 1000"]),
      m("Do users need different roles and permissions", ["Yes, many roles", "Yes, two or three", "No, all the same", "Not sure, please advise"]),
      m("Should the web app connect to other software", ["Yes, to the management system", "Yes, to payment tools", "No", "I do not know"]),
      m("How far along is the project", ["Just an idea", "I have some sketches", "I have a requirements document", "It exists and needs a rebuild"]),
      m("Should it also work well on phones", ["Yes, mostly on phones", "Yes, but it is used more on computers", "No, computers only", "Not sure, please advise"]),
      m("Do you need reports or statistics inside the web app", ["Yes, detailed", "Yes, the essentials", "No", "Not sure, please advise"]),
      m("Do you need support after the launch", ["Yes, ongoing", "Only for the first months", "No", "Not sure, please advise"]),
      m("When would you like the first version", ["Within three months", "Within six months", "Within a year", "No fixed deadline"]),
    ],
  },
  "UI/UX Design": {
    it: [
      m("Su cosa dobbiamo lavorare", ["Un sito", "Un'app per telefono", "Una web app o un gestionale", "Non saprei, consigliatemi voi"]),
      m("Il prodotto esiste già o è da progettare", ["Esiste e va migliorato", "Esiste e va rifatto", "È tutto da progettare", "È in sviluppo"]),
      m("Quante schermate pensi che servano", ["Meno di 10", "Da 10 a 30", "Più di 30", "Non saprei, consigliatemi voi"]),
      m("Ti serve anche un prototipo cliccabile", ["Sì", "No, bastano le schermate", "Più avanti", "Non saprei, consigliatemi voi"]),
      m("Vuoi fare test con utenti veri", ["Sì, prima di sviluppare", "Sì, dopo il lancio", "No", "Non saprei, consigliatemi voi"]),
      m("Ti serve una libreria di componenti riutilizzabili", ["Sì, completa", "Sì, essenziale", "No", "Non saprei, consigliatemi voi"]),
      m("Chi svilupperà il prodotto dopo il design", ["Un team interno", "Un'altra agenzia", "Voi", "Non è ancora deciso"]),
      m("Qual è il problema principale da risolvere", ["È difficile da usare", "È poco attraente", "Gli utenti abbandonano", "Manca ancora tutto"]),
      m("Chi sono soprattutto gli utenti", ["Clienti privati", "Aziende", "Dipendenti interni", "Un po' di tutto"]),
      m("Entro quando ti serve il design completo", ["Entro un mese", "Entro tre mesi", "Entro sei mesi", "Non ho una scadenza precisa"]),
    ],
    en: [
      m("What should we work on", ["A website", "A mobile app", "A web app or management software", "Not sure, please advise"]),
      m("Does the product already exist or is it to be designed", ["It exists and needs improving", "It exists and needs a redo", "It is all to be designed", "It is in development"]),
      m("How many screens do you think are needed", ["Fewer than 10", "10 to 30", "More than 30", "Not sure, please advise"]),
      m("Do you also need a clickable prototype", ["Yes", "No, the screens are enough", "Later on", "Not sure, please advise"]),
      m("Would you like to test with real users", ["Yes, before development", "Yes, after the launch", "No", "Not sure, please advise"]),
      m("Do you need a library of reusable components", ["Yes, a complete one", "Yes, the essentials", "No", "Not sure, please advise"]),
      m("Who will build the product after the design", ["An in-house team", "Another agency", "You", "Not decided yet"]),
      m("What is the main problem to solve", ["It is hard to use", "It does not look appealing", "Users drop off", "Everything is still missing"]),
      m("Who are the users mainly", ["Consumers", "Businesses", "Internal employees", "A bit of everyone"]),
      m("When do you need the complete design", ["Within a month", "Within three months", "Within six months", "No fixed deadline"]),
    ],
  },
};

module.exports = { RISERVA };
